const actionTypes = {
   ADD_PRODUCTS:'ADD_PRODUCTS',
   ADD_PRODUCTS_PROMOTIONS:'ADD_PRODUCTS_PROMOTIONS',
   ADD_ACTIVE_PROMOTIONS:'ADD_ACTIVE_PROMOTIONS',
   ADD_DEPARTMENTS:'ADD_DEPARTMENTS',
   SET_CURRENT_PAGE:'SET_CURRENT_PAGE',
   FILTER_DEPARTMENT:'FILTER_DEPARTMENT',
   FILTER_PROMOTION:'FILTER_PROMOTION',
   SEARCH_PRODUCT :'SEARCH_PRODUCT'
      }
      
      export default actionTypes;
      